/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Funcoes_DAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Laboratorio-Info
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
      //  RESULTADO_TXT.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SOMAR_BTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        VALOR1_TXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        VALOR2_TXT = new javax.swing.JTextField();
        SAIR_BTN = new javax.swing.JButton();
        RESULTADO_TXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RESULTADO2_TXT = new javax.swing.JLabel();
        SUBTRAIR_BTN = new javax.swing.JButton();
        DIVIDIR_BTN = new javax.swing.JButton();
        MULTIPLICAR_BTN = new javax.swing.JButton();
        PORCENTAGEM_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        SOMAR_BTN.setText("+");
        SOMAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOMAR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(SOMAR_BTN);
        SOMAR_BTN.setBounds(20, 210, 41, 25);

        jLabel1.setText("Valor 1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 60, 41, 16);

        VALOR1_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VALOR1_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(VALOR1_TXT);
        VALOR1_TXT.setBounds(130, 80, 70, 22);

        jLabel2.setText("Resultado  ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 160, 90, 16);

        VALOR2_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VALOR2_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(VALOR2_TXT);
        VALOR2_TXT.setBounds(130, 130, 69, 22);

        SAIR_BTN.setText("Sair");
        SAIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(SAIR_BTN);
        SAIR_BTN.setBounds(291, 49, 55, 25);

        RESULTADO_TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESULTADO_TXTActionPerformed(evt);
            }
        });
        jPanel1.add(RESULTADO_TXT);
        RESULTADO_TXT.setBounds(130, 180, 69, 22);

        jLabel3.setText("Valor 2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 110, 41, 16);
        jPanel1.add(RESULTADO2_TXT);
        RESULTADO2_TXT.setBounds(150, 260, 0, 0);

        SUBTRAIR_BTN.setText("-");
        jPanel1.add(SUBTRAIR_BTN);
        SUBTRAIR_BTN.setBounds(80, 210, 40, 25);

        DIVIDIR_BTN.setText("/");
        jPanel1.add(DIVIDIR_BTN);
        DIVIDIR_BTN.setBounds(240, 210, 37, 25);

        MULTIPLICAR_BTN.setText("X");
        jPanel1.add(MULTIPLICAR_BTN);
        MULTIPLICAR_BTN.setBounds(310, 210, 40, 25);

        PORCENTAGEM_BTN.setText("%");
        jPanel1.add(PORCENTAGEM_BTN);
        PORCENTAGEM_BTN.setBounds(150, 210, 50, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SOMAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOMAR_BTNActionPerformed
       Funcoes_DAO.soma();
        
    }//GEN-LAST:event_SOMAR_BTNActionPerformed

    private void VALOR1_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VALOR1_TXTActionPerformed
        
         
    }//GEN-LAST:event_VALOR1_TXTActionPerformed

    private void VALOR2_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VALOR2_TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VALOR2_TXTActionPerformed

    private void RESULTADO_TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESULTADO_TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RESULTADO_TXTActionPerformed

    private void SAIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIR_BTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SAIR_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DIVIDIR_BTN;
    private javax.swing.JButton MULTIPLICAR_BTN;
    private javax.swing.JButton PORCENTAGEM_BTN;
    public static javax.swing.JLabel RESULTADO2_TXT;
    public static javax.swing.JTextField RESULTADO_TXT;
    private javax.swing.JButton SAIR_BTN;
    private javax.swing.JButton SOMAR_BTN;
    private javax.swing.JButton SUBTRAIR_BTN;
    public static javax.swing.JTextField VALOR1_TXT;
    public static javax.swing.JTextField VALOR2_TXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
